Create Taichi Lang Weekly 20220420
taichi-dev/community pull request #6
Opened 2022-04-20 08:56 UTC by lucywsq

2022-04-20 08:57 UTC, lucywsq commented
PTAL @gingerkidney @ailzhang @Vissidarte-Herman Thanks a lot!

2022-04-21 06:58 UTC, Vissidarte-Herman requested changes

2022-04-21 06:58 UTC, Vissidarte-Herman commented on weekly/2022-04-21-Taichi-Lang-Weekly.md
> +- @[Trinkle23897](https://github.com/Trinkle23897) launched a toy project [**called Fast-Poisson-Image-Editing**](https://github.com/Trinkle23897/Fast-Poisson-Image-Editing) with Taichi extension.
```suggestion
- @[Trinkle23897](https://github.com/Trinkle23897) launched a fun project [**called Fast-Poisson-Image-Editing**](https://github.com/Trinkle23897/Fast-Poisson-Image-Editing) using Taichi as its extension. 
```

2022-04-21 06:59 UTC, Vissidarte-Herman commented
@lucywsq Please add ailing and yanqing as reviewer.

2022-04-22 03:48 UTC, lucywsq commented on weekly/2022-04-21-Taichi-Lang-Weekly.md
> +- @[Trinkle23897](https://github.com/Trinkle23897) launched a toy project [**called Fast-Poisson-Image-Editing**](https://github.com/Trinkle23897/Fast-Poisson-Image-Editing) with Taichi extension.
Done👌Thanks a lot.

2022-04-22 06:58 UTC, gingerkidney approved these changes

2022-04-22 07:00 UTC, gingerkidney commented on weekly/2022-04-21-Taichi-Lang-Weekly.md
> +- @[Trinkle23897](https://github.com/Trinkle23897) launched a fun project [**called Fast-Poisson-Image-Editing**](https://github.com/Trinkle23897/Fast-Poisson-Image-Editing) using Taichi as its exten
```suggestion
- @[Trinkle23897](https://github.com/Trinkle23897) launched a fun project called [**Fast-Poisson-Image-Editing**](https://github.com/Trinkle23897/Fast-Poisson-Image-Editing) using Taichi as its extension. 
```

2022-04-22 08:30 UTC, merged

2022-05-06 07:11 UTC, gingerkidney commented on weekly/2022-04-21-Taichi-Lang-Weekly.md
> +* 2022/04/21 | Online | Meetup
should add voxel challenge

2022-05-06 07:12 UTC, gingerkidney commented on weekly/2022-04-21-Taichi-Lang-Weekly.md
> +* 2022/04/21 | Online | Meetup
I suggest adding the voxel challenge at the top of the weekly